version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: internship-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Piyush@12345
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - internship-network

networks:
  internship-network:
    driver: bridge

volumes:
  sqlserver-data:
